config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :scholar do
    get 'statistics', 'explore', controller: 'pages'
    resources :forums, only: %i[index show create update destroy]
    resources :posts, only: %i[index show create update destroy] do
      get :clusters, on: :member
      get :visualization, on: :member
      post :segment, on: :member
      post :sentiment_analysis, on: :member
      post :compute_embedding, on: :member
    end
  end

  namespace :admin do
    require 'sidekiq/web'
    authenticate :user, ->(user) { user.is_admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end
    resources :users, only: %i[index update destroy]
  end

  root to: 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_alert.html.erb
<div id="flash">
  <% flash.each do |type, message| %>
    <%= bootstrap_alert(message, type) %>
  <% end %>
</div>

app/views/shared/_alert.js.erb
<% alert.each do |key, value| %>
  $('#flash').append('<%= bootstrap_alert(value, key) %>')
<% end %>

app/views/shared/_logo.html.erb
<div class="text-center my-4">
  <h1>
    <%= link_to root_path, class: 'text-decoration-none text-dark' do %>
      <%= image_tag 'logo', height: '100px'%>
    <% end %>
    <% if user_signed_in? %>
      <span>
        <%= link_to destroy_user_session_path, method: :delete, class: 'ml-4 btn btn-sm btn-outline-secondary' do %>
          <i class="fas fa-sign-out-alt"></i> Sign out
        <% end %>
      </span>
    <% end %>
  </h1>
</div>

app/views/shared/_tabs.html.erb
<%= render 'shared/logo' %>
<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to 'Forums', scholar_forums_path, class: 'nav-link', id: 'tab-forums' %>
  </li>
  <li class="nav-item">
    <%= link_to 'Posts', scholar_posts_path, class: 'nav-link', id: 'tab-posts' %>
  </li>
  <li class="nav-item">
    <%= link_to 'Explore', scholar_explore_path, class: 'nav-link', id: 'tab-explore' %>
  </li>
  <li class="nav-item">
    <%= link_to 'Statistics', scholar_statistics_path, class: 'nav-link', id: 'tab-statistics' %>
  </li>
  <% if current_user.is_admin? %>
    <li class="nav-item">
      <%= link_to 'Users', admin_users_path, class: 'nav-link', id: 'tab-users' %>
    </li>
    <li class="nav-item">
      <%= link_to 'Sidekiq', admin_sidekiq_web_path, target: :_blank, class: 'nav-link', id: 'tab-sidekiq' %>
    </li>
  <% end %>
</ul>
<script type="text/javascript">
  paths = window.location.pathname.split('/')
  $(`#tab-${paths[2]}`).addClass('active')
</script>
<br>