config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :scholar do
    get 'statistics', 'explore', controller: 'pages'
    resources :forums, only: %i[index show create update destroy]
    resources :posts, only: %i[index show create update destroy] do
      get :clusters, on: :member
      get :visualization, on: :member
      post :segment, on: :member
      post :sentiment_analysis, on: :member
      post :compute_embedding, on: :member
    end
  end

  namespace :admin do
    require 'sidekiq/web'
    authenticate :user, ->(user) { user.is_admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end
    resources :users, only: %i[index update destroy]
  end

  root to: 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  include Mentionable

  belongs_to :forum, counter_cache: true
  has_one :sentiment, as: :sentimental, dependent: :destroy
  has_many :comments, dependent: :destroy

  scope :not_removed, -> { where(removed: nil) }
  scope :crawled, -> { where('comment_count = comments_count') }
  scope :comments_more_then, ->(number) { where('comments_count >= ?', number) }
  scope :reviewable, -> { not_removed.crawled.comments_more_then(10) }
  scope :random, -> { offset(rand(count)) } # need 2 sql query

  validates_uniqueness_of :dcard_id

  def dcard_url
    "https://www.dcard.tw/f/#{forum_alias}/p/#{dcard_id}"
  end

  def floor
    0
  end
end

app/models/scholar.rb
module Scholar
  def self.table_name_prefix
    ''
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController
  before_action :set_post, except: %i[index create]
  before_action :set_comments, only: %i[show visualization]

  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).order(id: :desc).page(params[:page])
  end

  def show
    @comments = @comments.page(params[:page])
  end

  def create
    forum = Forum.find_by!(name: post_params[:forum_name])
    @post = Post.new(post_params)
    @post.forum = forum
    @alert = {}
    if @post.save
      Dcard::UpdatePostJob.perform_later(@post)
      @alert[:notice] = "Crawling comments of Post #{@post.dcard_id}, you can refresh your browser to read it."
    else
      @alert[:alert] = "Can not crawl this Post from #{@post.dcard_url}, maybe you already crawled it."
    end
    respond_to do |format|
      format.html { redirect_back({ fallback_location: admin_posts_path }.merge(@alert)) }
      format.js
    end
  end

  def update
    Dcard::UpdatePostJob.perform_later(@post)
    @alert = { notice: "Crawling comments of Post #{@post.dcard_id}, you can refresh your browser to read it." }
    respond_to do |format|
      format.html { redirect_back({ fallback_location: admin_posts_path }.merge(@alert)) }
      format.js
    end
  end

  def destroy
    @post.destroy
    redirect_to admin_posts_url, notice: 'Post was successfully destroyed.'
  end

  def clusters
    @kmeans = OpinionsClusterJob.perform_now @post, params.fetch(:k) { 1 }
    @clusters = @kmeans.clusters.map { |cluster| @post.comments.where(floor: cluster.points.map(&:label)).includes(:sentiment).order(floor: :asc) }
  end

  def visualization
    if params[:k]
      @kmeans = OpinionsClusterJob.perform_now @post, params[:k]
      @clusters = @kmeans&.clusters&.map { |cluster| cluster.points.map(&:label) }
    else
      k = BestOpinionsClusterJob.perform_now(@post).k
      redirect_to visualization_admin_post_path(@post, k: k)
    end
  rescue StandardError => e
    flash[:alert] = e
    @kmeans = nil
  end

  def segment
    text = [@post.content]
    @post.comments.order(floor: :asc).each do |comment|
      text << comment.content if comment.content.present?
    end
    method = params.fetch(:method, 'jieba')
    @segmentation = Segmentation::Service.new.perform(text, method)
    respond_to do |format|
      format.text { response.headers['Content-Disposition'] = "attachment; filename=\"dcard-#{@post.dcard_id}-#{method}.txt\"" }
      format.xlsx { render xlsx: 'segment', filename: "dcard-#{@post.dcard_id}-#{method}.xlsx" }
    end
  end

  def sentiment_analysis
    Baidu::GetPostSentimentJob.perform_later(@post)
    @alert = { notice: "Scheduling sentiment analysis of Post #{@post.dcard_id} and its comments." }
    respond_to do |format|
      format.html { redirect_back({ fallback_location: admin_posts_path }.merge(@alert)) }
      format.js
    end
  end

  def compute_embedding
    Bert::GetPostEmbeddingJob.perform_later(@post)
    @alert = { notice: "Scheduling compute embedding of Post #{@post.dcard_id} and its comments." }
    respond_to do |format|
      format.html { redirect_back({ fallback_location: admin_posts_path }.merge(@alert)) }
      format.js
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def set_comments
    @comments = @post.comments.includes(:sentiment).order(floor: :asc)
  end

  def post_params
    params.require(:post).permit(:dcard_id, :forum_name)
  end
end

app/controllers/scholar/base_controller.rb
class Scholar::BaseController < ApplicationController
  before_action :authenticate_user!
  before_action :auth_scholar

  private

  def auth_scholar
    return if current_user.is_scholar

    redirect_to root_path, alert: 'You are not scholar.'
  end
end

app/controllers/scholar/forums_controller.rb
class Scholar::ForumsController < Scholar::BaseController
  before_action :set_forum, only: %i[show update destroy]

  def index
    @q = Forum.ransack(params[:q])
    @forums = @q.result(distinct: true).page(params[:page])
  end

  def show; end

  def create
    Dcard::UpdateForumsJob.perform_later
    redirect_back fallback_location: scholar_forums_path, notice: 'Crawling every forums, you can refresh your browser to read it.'
  end

  def update
    Dcard::GetForumPostsJob.perform_later(@forum)
    @alert = { notice: "Crawling posts of forum #{@forum.id}, you can refresh your browser to read it." }
    respond_to do |format|
      format.html { redirect_back({ fallback_location: scholar_posts_path }.merge(@alert)) }
      format.js
    end
  end

  def destroy
    @forum.destroy
    redirect_to scholar_forums_url, notice: "Forum #{@forum.name} was successfully destroyed."
  end

  private

  def set_forum
    @forum = Forum.find(params[:id])
  end
end

app/controllers/scholar/pages_controller.rb
class Scholar::PagesController < Scholar::BaseController
  def statistics
    @forums_count = Forum.count
    @posts_count = Post.count
    @comments_count = Comment.count
    @users_count = User.count
    @sentiments_count = Sentiment.count
  end

  def explore
    @posts = []
    @exist_posts = []
    query = params[:query]
    forum = params[:forum]
    posts_json = if query.blank?
                   Dcard::Post.get(popular: true, forum: forum)
                 else
                   Dcard::Post.search(query: query, forum: forum)
                 end
    if posts_json.class == Hash && posts_json[:error].present?
      flash[:notice] = 'Something wrong when searching on Dcard.'
    else
      @posts = Dcard::Post.to_records(posts_json)
      @exist_posts = Post.where(dcard_id: @posts.map(&:dcard_id))
      flash[:notice] = "We found #{@posts.size} Posts about #{query} on Dcard."
    end
  end
end

app/controllers/scholar/posts_controller.rb
class Scholar::PostsController < Scholar::BaseController
  before_action :set_post, except: %i[index create]
  before_action :set_comments, only: %i[show visualization]

  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).order(id: :desc).page(params[:page])
  end

  def show
    @comments = @comments.page(params[:page])
  end

  def create
    forum = Forum.find_by!(name: post_params[:forum_name])
    @post = Post.new(post_params)
    @post.forum = forum
    @alert = {}
    if @post.save
      Dcard::UpdatePostJob.perform_later(@post)
      @alert[:notice] = "Crawling comments of Post #{@post.dcard_id}, you can refresh your browser to read it."
    else
      @alert[:alert] = "Can not crawl this Post from #{@post.dcard_url}, maybe you already crawled it."
    end
    respond_to do |format|
      format.html { redirect_back({ fallback_location: scholar_posts_path }.merge(@alert)) }
      format.js
    end
  end

  def update
    Dcard::UpdatePostJob.perform_later(@post)
    @alert = { notice: "Crawling comments of Post #{@post.dcard_id}, you can refresh your browser to read it." }
    respond_to do |format|
      format.html { redirect_back({ fallback_location: scholar_posts_path }.merge(@alert)) }
      format.js
    end
  end

  def destroy
    @post.destroy
    redirect_to scholar_posts_url, notice: 'Post was successfully destroyed.'
  end

  def clusters
    @kmeans = OpinionsClusterJob.perform_now @post, params.fetch(:k) { 1 }
    @clusters = @kmeans.clusters.map { |cluster| @post.comments.where(floor: cluster.points.map(&:label)).includes(:sentiment).order(floor: :asc) }
  end

  def visualization
    begin
      if params[:k]
        @kmeans = OpinionsClusterJob.perform_now @post, params[:k]
        @clusters = @kmeans&.clusters&.map { |cluster| cluster.points.map(&:label) }
      else
        k = BestOpinionsClusterJob.perform_now(@post).k
        redirect_to visualization_scholar_post_path(@post, k: k)
      end
    rescue StandardError => e
      flash[:alert] = e
      @kmeans = nil
    end

    text = [content_filter(@post.content)]
    @comments.each do |comment|
      text << content_filter(comment.content) if comment.content.present?
    end
    @segmentation = Segmentation::Service.new.perform(text, 'jieba')
  end

  def segment
    text = [@post.content]
    @post.comments.order(floor: :asc).each do |comment|
      text << comment.content if comment.content.present?
    end
    method = params.fetch(:method, 'jieba')
    @segmentation = Segmentation::Service.new.perform(text, method)
    respond_to do |format|
      format.text { response.headers['Content-Disposition'] = "attachment; filename=\"dcard-#{@post.dcard_id}-#{method}.txt\"" }
      format.xlsx { render xlsx: 'segment', filename: "dcard-#{@post.dcard_id}-#{method}.xlsx" }
    end
  end

  def sentiment_analysis
    Baidu::GetPostSentimentJob.perform_later(@post)
    @alert = { notice: "Scheduling sentiment analysis of Post #{@post.dcard_id} and its comments." }
    respond_to do |format|
      format.html { redirect_back({ fallback_location: scholar_posts_path }.merge(@alert)) }
      format.js
    end
  end

  def compute_embedding
    Bert::GetPostEmbeddingJob.perform_later(@post)
    @alert = { notice: "Scheduling compute embedding of Post #{@post.dcard_id} and its comments." }
    respond_to do |format|
      format.html { redirect_back({ fallback_location: scholar_posts_path }.merge(@alert)) }
      format.js
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def set_comments
    @comments = @post.comments.includes(:sentiment).order(floor: :asc)
  end

  def post_params
    params.require(:post).permit(:dcard_id, :forum_name)
  end

  def content_filter(content)
    return '' if content.blank?
    content = content.gsub(URI::DEFAULT_PARSER.make_regexp, '') # remove url
    content = content.gsub(/[bB]\d+/, '')  # remove mentions
  end
end

app/views/scholar/posts/_post.html.erb
<%= dcard_html(post) %>
<% (comments ||= post.comments.includes(:sentiment).order(:floor)).each do |comment| %>
  <%= dcard_html(comment) %>
<% end  %>

app/views/scholar/posts/_tasks_btn.html.erb
<div class="dropdown <%= klass ||= '' %>">
  <div class="btn btn-sm btn-outline-secondary dropdown-toggle" data-toggle="dropdown">
    <i class="fas fa-tasks"></i> Tasks
  </div>
  <div class="dropdown-menu">
    <%= link_to scholar_post_path(post), method: :patch, remote: true, class: 'dropdown-item', id: "crawl-post-#{post.dcard_id}-btn" do %>
      <i class="fas fa-cloud-download-alt"></i> Crawl
    <% end %>
    <%= link_to sentiment_analysis_scholar_post_path(post), method: :post, remote: true, class: 'dropdown-item', id: "sentiment-analysis-post-#{post.dcard_id}-btn" do %>
      <i class="fas fa-smile"></i> Sentiment Analysis
    <% end %>
    <%= link_to compute_embedding_scholar_post_path(post), method: :post, remote: true, class: 'dropdown-item', id: "compute-embedding-post-#{post.dcard_id}-btn" do %>
      <i class="fas fa-vector-square"></i> Compute Embedding
    <% end %>
    <div class="dropdown-header"><i class="fas fa-file-download"></i> Segment by</div>
    <table class="table table-bordered table-responsive dropdown-item">
      <tbody>
        <tr>
          <th>jieba</th>
          <td>
            <%= link_to '.txt', segment_scholar_post_path(post, method: 'jieba', format: :text), method: :post %>
            or
            <%= link_to '.xlsx', segment_scholar_post_path(post, method: 'jieba', format: :xlsx), method: :post %>
          </td>
        </tr>
        <tr>
          <th>snownlp</th>
          <td>
            <%= link_to '.txt', segment_scholar_post_path(post, method: 'snownlp', format: :text), method: :post %>
            or
            <%= link_to '.xlsx', segment_scholar_post_path(post, method: 'snownlp', format: :xlsx), method: :post %>
          </td>
        </tr>
        <tr>
          <th>pkuseg</th>
          <td>
            <%= link_to '.txt', segment_scholar_post_path(post, method: 'pkuseg', format: :text), method: :post %>
            or
            <%= link_to '.xlsx', segment_scholar_post_path(post, method: 'pkuseg', format: :xlsx), method: :post %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/scholar/posts/compute_embedding.js.erb
<%= render 'shared/alert', alert: @alert %>
$('#compute-embedding-post-<%= @post.dcard_id %>-btn').addClass('disabled').text('Computed')

app/views/scholar/posts/create.js.erb
<%= render 'shared/alert', alert: @alert %>
$('#crawl-post-<%= @post.dcard_id %>-btn').addClass('disabled').text('Crawled')

app/views/scholar/posts/segment.text.erb
<% @segmentation.each do |words| %>
<%= words.join(' ').gsub(/\n /, "\n") %>

<% end %>

app/views/scholar/posts/sentiment_analysis.js.erb
<%= render 'shared/alert', alert: @alert %>
$('#sentiment-analysis-post-<%= @post.dcard_id %>-btn').addClass('disabled').text('Analyzed')

app/views/scholar/posts/show.html.erb
<%= render 'shared/tabs' %>
<div class="container">
  <div class="btn-toolbar mt-2">
    <%= link_to scholar_posts_path, class: 'btn btn-sm btn-outline-secondary' do %>
      <i class="fas fa-redo"></i> Back
    <% end %>
    <%= link_to visualization_scholar_post_path(@post, k: 1), class: 'btn btn-sm btn-outline-secondary ml-auto' do %>
      <i class="fas fa-braille"></i> Visualization
    <% end %>
    <%= render 'tasks_btn', post: @post, klass: 'ml-1' %>
    <%= link_to scholar_post_path(@post), class: 'btn btn-sm btn-outline-danger ml-1', method: :delete, data: { confirm: 'Are you sure?' } do %>
      <i class="fas fa-trash"></i>
    <% end %>
  </div>
  <p class="mt-2"><%= link_to @post.forum_name, scholar_forum_path(@post.forum_id) %> / <%= @post.title %></p>
  <div class="mt-2">
    <%= paginate @comments %>
    <%= render 'post', post: @post, comments: @comments %>
    <%= paginate @comments %>
  </div>
</div>

app/views/scholar/posts/update.js.erb
<%= render 'shared/alert', alert: @alert %>
$('#crawl-post-<%= @post.dcard_id %>-btn').addClass('disabled').text('Crawled')

app/views/scholar/posts/visualization.html.erb
<%= render 'shared/tabs' %>
<div class="container my-2">
  <div class="btn-toolbar">
    <%= link_to scholar_post_path, class: 'btn btn-sm btn-outline-secondary mr-auto' do %>
      <i class="fas fa-redo"></i> Back
    <% end %>
    <%= render 'tasks_btn', post: @post %>
  </div>
  <div class="mt-2">
    <p><%= link_to @post.forum_name, scholar_forum_path(@post.forum_id) %> / <%= @post.title %></p>
    <% unless @kmeans.present? %>
      <p>
        You need to
        <%= link_to compute_embedding_scholar_post_path(@post), method: :post, remote: true, class: 'btn btn-sm btn-outline-warning', id: "compute-embedding-post-#{@post.dcard_id}-btn" do %>
          <i class="fas fa-vector-square"></i> Compute Embedding
        <% end %>
        first
      </p>
    <% end %>
    <% unless @post.sentiment.present? %>
      <p>
        You need to
        <%= link_to sentiment_analysis_scholar_post_path(@post), method: :post, remote: true, class: 'btn btn-sm btn-outline-warning', id: "sentiment-analysis-post-#{@post.dcard_id}-btn" do %>
          <i class="fas fa-smile"></i> Sentiment Analysis
        <% end %>
        first
      </p>
    <% end %>
  </div>
  <hr>
  <div>
    <h2>Word Cloud</h2>
    <div class="row">
      <div id="word-cloud-container" class="col-12">
        <canvas id="word-cloud" height="300"></canvas>
      </div>
    </div>
  </div>
  <hr>
  <div>
    <h2>Sentiment Analysis</h2>
    <div class="row">
      <div id="sentiment-pie-chart-container" class="col-md-6 col-12"></div>
      <div id="sentiment-column-chart-container" class="col-md-6 col-12"></div>
    </div>
  </div>
  <hr>
  <div>
    <h2>Mention Graph</h2>
    <% if @kmeans %>
      <%= form_tag visualization_scholar_post_path(@post), method: :get, class: "form-inline" do %>
        <div class="form-group mr-2">
          <label class="mr-1">K :</label>
          <%= number_field_tag :k, @kmeans.k, class: "form-control" %>
        </div>
        <button type="submit" class="btn btn-sm btn-outline-secondary">
          <i class="fas fa-paper-plane"></i> Cluster
        </button>
        <%= link_to visualization_scholar_post_path(@post), class: 'btn btn-sm btn-outline-secondary ml-2' do %>
          <i class="fas fa-braille"></i> Best K
        <% end %>
      <% end %>
      <p class="text-muted small">Silhouette score: <%= @kmeans.silhouette.round(5) %></p>
    <% end %>
    <input type="text" id="floor-range" name="floor-range">
    <div class="row mt-2">
      <div class="col-12 col-md-7">
        <div id="graph-container">
          <div id="graph"></div>
        </div>
        <div class="btn-toolbar mt-2">
          <label>Color by</label>
          <div class="btn-group btn-group-toggle ml-1 mr-2" data-toggle="buttons">
            <div class="btn btn-sm btn-outline-secondary active" id="color-by-gender-btn"><input type="radio">Gender</div>
            <div class="btn btn-sm btn-outline-secondary" id="color-by-sentiment-btn"><input type="radio">Sentiment</div>
            <div class="btn btn-sm btn-outline-secondary" id="color-by-cluster-btn"><input type="radio">Cluster</div>
          </div>
          <label>Size by</label>
          <div class="btn-group btn-group-toggle ml-1 mr-2" data-toggle="buttons">
            <div class="btn btn-sm btn-outline-secondary active" id="size-by-like-btn"><input type="radio">Like</div>
            <div class="btn btn-sm btn-outline-secondary" id="size-by-length-btn"><input type="radio">Length</div>
          </div>
        </div>
      </div>
      <div class="col-12 col-md-5">
        <div id="node-html"></div>
      </div>
    </div>
  </div>
</div>
<script>
  var cloud = document.getElementById('word-cloud')
  var cloudContainer = document.getElementById('word-cloud-container')
  cloud.width = cloudContainer.clientWidth
  WordCloud(cloud, { list: <%= sanitize word_frequency(@segmentation).to_json %>, minSize: 12, weightFactor: 6 })
  var data = <%= sanitize force_graph_data_formater(@post, @comments).to_json %>
  function dates(from, to) {
    const fromDay = dayjs(from)
    const toDay = dayjs(to)
    const result = []
    const days = toDay.diff(fromDay, 'day')
    for (let i = 0; i <= days; i++) {
      result.push(fromDay.add(i, 'day').format('YYYY-MM-DD HH:mm'))
    }
    return result
  }
  
  // Prepare pie chart data
  var pieChartData = [
    { name: 'negative', data: 0 },
    { name: 'neutral', data: 0 },
    { name: 'positive', data: 0 },
    { name: 'null', data: 0 }
  ]
  data.nodes.forEach(node => {
    if (node.sentiment === 'negative') {
      pieChartData[0].data += 1
    } else if (node.sentiment === 'neutral') {
      pieChartData[1].data += 1
    } else if (node.sentiment === 'positive') {
      pieChartData[2].data += 1
    } else {
      pieChartData[3].data += 1
    }
  })
  // Prepare column chart data
  var nodesGroupByDay = _.groupBy(data.nodes, (node) => dayjs.unix(node.createdAt).startOf('day').format('YYYY-MM-DD HH:mm'))
  var columnChartCategories = dates(_.findKey(nodesGroupByDay), _.findLastKey(nodesGroupByDay))
  var columnChartColumnData = [
    { name: 'negative', data: [] },
    { name: 'neutral', data: [] },
    { name: 'positive', data: [] },
    { name: 'null', data: [] }
  ]
  var columnChartLineData = [
    { name: 'total', data: [] }
  ]
  
  _.forEach(columnChartCategories, (day, index) => {
    columnChartColumnData.forEach(column => {
      column.data[index] = 0
    })
    columnChartLineData.forEach(line => {
      line.data[index] = 0
    })
    day
    _.forEach(nodesGroupByDay[day], node => {
      columnChartLineData[0].data[index] += 1
      if (node.sentiment === 'negative') {
        columnChartColumnData[0].data[index] += 1
      } else if (node.sentiment === 'neutral') {
        columnChartColumnData[1].data[index] += 1
      } else if (node.sentiment === 'positive') {
        columnChartColumnData[2].data[index] += 1
      } else {
        columnChartColumnData[3].data[index] += 1
      }
    })
  })
  
  var sentimentColors = [
    "rgba(220,53,69,1)", // negative
    "rgba(40,167,69,1)", // neutral
    "rgba(0,123,255,1)", // positive
    "rgba(108,117,125,1)" // null
  ]
  
  // Draw pie chart
  tui.chart.registerTheme('pie', { series: { colors: sentimentColors }})
  tui.chart.pieChart(document.getElementById('sentiment-pie-chart-container'), {
      categories: ['Comment'],
      series: pieChartData
    }, {
      theme: 'pie'
    }
  )
  
  // Draw column chart
  tui.chart.registerTheme('combo', { series: { column: { colors: sentimentColors }}})
  tui.chart.comboChart(document.getElementById('sentiment-column-chart-container'), {
      categories: columnChartCategories,
      series: {
        column: columnChartColumnData,
        line: columnChartLineData
      }
    }, {
      // options
      xAxis: {
        type: 'datetime',
        dateFormat: 'YYYY-MM-DD'
      },
      series: {
        zoomable: true
      },
      theme: 'combo'
    }
  )
  
  // Draw graph
  var clusters = <%= sanitize @clusters.to_json %> || []
  var Graph = ForceGraph3D()
  var graph = document.getElementById('graph')
  var graphContainer = document.getElementById('graph-container')
  var nodeHtml = document.getElementById('node-html')
  function adjustGraphSize() {
    Graph.width(graphContainer.clientWidth).height(window.innerHeight - 100)
  }
  function removeChildren(dom) {
    while (dom.firstChild) { dom.removeChild(dom.firstChild) }
  }
  function showNode(node) {
    removeChildren(nodeHtml)
    nodeHtml.insertAdjacentHTML('afterbegin', node.html);
  }
  Graph(document.getElementById('graph'))
    .graphData(data)
    .backgroundColor('#f8f9fa')
    .nodeVal('valLike')
    .nodeColor('genderColor')
    .onNodeClick(node => showNode(node))
    .linkWidth(2)
  adjustGraphSize()
  window.addEventListener('resize', () => adjustGraphSize())
  // Button to controll graph
  document.getElementById('color-by-gender-btn').addEventListener('click', () => Graph.nodeColor('genderColor'))
  document.getElementById('color-by-sentiment-btn').addEventListener('click', () => Graph.nodeColor('sentimentColor'))
  document.getElementById('color-by-cluster-btn').addEventListener('click', () => Graph.nodeColor('clusterColor'))
  document.getElementById('size-by-like-btn').addEventListener('click', () => Graph.nodeVal('valLike'))
  document.getElementById('size-by-length-btn').addEventListener('click', () => Graph.nodeVal('valLength'))
  
  // Add clusters colors to nodes
  function randomColor() {
    let r = (Math.random() * 255) | 0
    let g = (Math.random() * 255) | 0
    let b = (Math.random() * 255) | 0
    return `rgb(${r}, ${g}, ${b})`
  }
  document.getElementById('color-by-cluster-btn').addEventListener('click', () => {
    clusters.forEach(cluster => {
      let color = randomColor()
      cluster.forEach(point => {
        let node = data.nodes.find(node => node.floor === point)
        node["clusterColor"] = color
      })
    })
  })
  
  // ionRangeSlider for display nodes in specific floors
  function showNodesInRange(min, max) {
    let { nodes, links } = data
    // Remove links attached to node
    links = links.filter(l => {
      return l.source.floor >= min &&
        l.source.floor <= max &&
        l.target.floor >= min &&
        l.target.floor <= max
    })
    // Remove nodes
    nodes = nodes.filter(n => n.floor >= min && n.floor <= max)
    Graph.graphData({ nodes, links })
    return {nodes, links}
  }
  $("#floor-range").ionRangeSlider({
    type: "double",
    grid: true,
    min: 0,
    max: data['nodes'][data['nodes'].length-1].floor,
    from: 0,
    to: data['nodes'][data['nodes'].length-1].floor,
    prefix: "B",
    onFinish: function (data) {
      console.log(`from ${data.from}`)
      console.log(`to ${data.to}`)
      showNodesInRange(data.from, data.to)
    }
  })
</script>
<style>
  img {
    max-width: 100%;
    max-height: 200px;
  }
</style>